I CMT_CPBP 12-01 20:34:33.106 run.py:58] get loaders
I CMT_CPBP 12-01 20:34:33.424 run.py:64] build graph, criterion, optimizer and trainer
I CMT_CPBP 12-01 20:34:36.299 run.py:103] start training
ARGS
Namespace(gpu_index=0, idx=2, load_rhythm=True, ngpu=1, optim_name='adam', restore_epoch=-1, sample=False, seed=42)
CONFIG
{'path': './pkl_files/instance_pkl_8bars_fpb12_48p_ckey', 'loader': {'num_workers': 8, 'batch_size': 64, 'shuffle': True, 'drop_last': True, 'pin_memory': True}, 'dataset': {'data_ratio': [0.8, 0.1, 0.1], 'num_worker': 4}}
Traceback (most recent call last):
  File "/home/lidem/projects/def-pesantg/lidem/CMT_CPBP/run.py", line 104, in <module>
    trainer.train(restore_epoch=args.restore_epoch, load_rhythm=args.load_rhythm)
  File "/lustre06/project/6032307/lidem/CMT_CPBP/trainer.py", line 112, in train
    self.load_model(kwargs["restore_epoch"], kwargs["load_rhythm"])
  File "/lustre06/project/6032307/lidem/CMT_CPBP/trainer.py", line 72, in load_model
    checkpoint = torch.load(rhythm_ckpt, map_location=self.device)
  File "/home/lidem/.local/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/lidem/.local/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/lidem/.local/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './results/idx001/model/checkpoint_100.pth.tar'
